### ISSUE TITLE
self.deribit.send_public

### ISSUE THREAD

**Issue by mrGreenS** [olned/ssc2ce-python#22]
Hello!
How can I add and delete subscriptions while the programm is working but not only after **self.deribit.send_public** is launched.

**Comment by olned** [comment]
Hello!

I didn't fully understand the question.
You can subscribe to or unsubscribe from a public or private subscription at any time by calling send_public or send_private, respectively.

```python
await self.deribit.send_public(request={
        "method": "public/subscribe",
        "params": {
            "channels": "deribit_price_index.btc_usd"
        }
    })
```

```python
await self.deribit.send_public(request={
        "method": "public/unsubscribe",
        "params": {
            "channels": "deribit_price_index.btc_usd"
        }
    })
```

If you are calling from a non-async method, you can use [asyncio.ensure_future](https://docs.python.org/3/library/asyncio-future.html#asyncio.ensure_future)

**Comment by mrGreenS** [comment]
The question is solved.
Thank you very much!
