### ISSUE TITLE
Connection to Deribit

### ISSUE THREAD

**Issue by mrGreenS** [olned/ssc2ce-python#23]
Hi!

We need to add "is_connected()" function or variable to your library. So that we could understand if we have a connection to Deribit platform.

**Comment by olned** [comment]
Hi!

Could you please give me a little more information about the use case, how do you plan to use this feature?
Do you want to check if you have already established a connection, or to check if the connection is closed, or you want to check if the connection is alive?

**Comment by mrGreenS** [comment]
If the connection is closed it is false
If the connection is active it is true

**Comment by olned** [comment]
Let me please clarify.
The is_connected function returns true if the connection was established and not closed, otherwise it returns false.

Right?

**Comment by mrGreenS** [comment]
yes.

**Comment by olned** [comment]
I added the `is_connected` method to the parent class, it is common to all connections.
An example you can see [here](https://github.com/olned/ssc2ce-python/blob/master/examples/deribit/check_is_connected.py)
